### ISSUE TITLE
urlWithCacheBusting and CDN problematic

### ISSUE THREAD

**Issue by chenav** [GoogleChrome/sw-precache#100]
Hello,

When using a CDN, the urlWithCacheBusting makes the CDN useless for app shell.
Indeed, the query string "myfile.js?sw-precache=thisismytime" makes each fetch request (of each new user) different from a CDN perspective. For each new service-worker enabled device, the CDN misses the "myfile.js?sw-cache=newtime" request and goes to the origin HTTP server. 
Each time a new service worker gets installed. Even if the file has not changed. 
It creates a growing cache on the CDN and costs in terms of bandwith to the origin server.
Especially when an app shell may have numerous files. 
I just realized it when I understood the MISS spikes I had in Fastly CDN came from the cache-busting  :)

When using a CDN, I guess, it means you usually are responsible of the app shell version (which is "quite" stable), and you might not need cachebusting strategy in the SW. In this case, the cacheId option is enough (very simple and efficient)
Of course, it could be possible in theory to write specific rules in the CDN to make it agnostic to the "?sw-cache" or "&sw-cache" attributes. But it is not that smart (you have to do it for each url in Fastly for instance, or to ask for a custom VCL script to the support team) and it creates complexity. 

Could it be possible to create an option "useUrlWithCacheBusting" (true/false) in sw-precache ?
Or maybe, it is already there somehow, but I did not find a straightforward solution.
Right now, the easiest way I found was to manually modify the code generated by the grunt build. Which is bad :)

What do you think ? 

Cheers.

Chenav

**Comment by jeffposnick** [comment]
What's the caching policy that's set on responses from your CDN? Unless the CDN has caching disabled entirely, it's not safe to have `sw-precache` fetch the URL without cache-busting, because it might lead to a response that was previously cached on the CDN being used to fulfill what is meant to be a request for an updated resource. And then that stale response would be reused by `sw-precache` indefinitely.

There are two scenarios in which disabling cache-busting is safe:
1. When you know that the HTTP server + any proxies never caches.
2. When you know that 100% of your HTTP requests, including those for your HTML landing pages, will already include versioning info via something like [`gulp-rev`](https://github.com/sindresorhus/gulp-rev).

Scenario 1. might be the case for some folks (which is what I'm asking you about), but 2. is very unlikely to be true—how many web sites serve their landing pages with URLs like `index-abcd1234.html`? I don't want to make it too easy for folks to shoot themselves in the foot by disabling cache-busting.

What should be doable, though, is including in the hash revision for a given file as the cache-busting parameter instead of each client browser's local timestamp. That would mean fewer unique URLs that your CDN would see. How does that sound?

**Comment by chenav** [comment]
I am in scenario 1 case. 
I am using an "Origin Shield Architecture" (as they call it) in the CDN, i.e. one of the CDN edge is the "reference" for all CDN edges. This reference edge could be considered actually, as the "cache". 
The HTTP server on my side does not cache anything then (regarding app shell files).
Each new version of the app shell (result of a grunt process), will purge the previous  app shell files in the CDN Origin Shield edge through a very simple API actually. Then a cascade style operation purges the other edges (Varnish within Fastly does it in around 200 ms, which is I must say, quite amazing).
As a matter of fact, at a given time, there is one version "for sure" available in the CDN edges.
The HTTP server delivers the app shell files, only once.
That's why the cache-busting parameter, set with each client browser's local timestamp is a CDN killer in that case :)

I understand your concern, and I have to agree with you.
But with a cache-busting parameter set with a hash revision (global or for a given file), we have a winner in all scenarios.
That sounds great.

**Comment by chenav** [comment]
Could you please publish it to the npm registry ? 
Thanks a lot for the fix ! 

Chenav

**Comment by jeffposnick** [comment]
Sorry about that—I'm aiming to cut a new release the week of May 23. In the meantime, feel free to explicitly pull in the version you want based on the commit hash.

**Comment by jeffposnick** [comment]
`3.2.0` is out!
