### ISSUE TITLE
Clarify routing

### ISSUE THREAD

**Issue by wernight** [GoogleChrome/sw-precache#128]
Frequently routing may overlap and it should document what happens.

Example:

    staticFileGlobs: ['foo'],
    runtimeCaching: [{
      urlPattern: /.*/,
      handler: 'fastest',
    }]

In that case:

- Does one takes precedence over the others? (so far it seems that they would **both** cache; if I'm wrong, need to describe if order matters).
- How to set the default sw-toolbox caching in sw-precache?

It's even harder given that there is no option showing if it worked and through which way at runtime (in the browser console).

**Comment by jeffposnick** [comment]
So this just came up in https://github.com/Polymer/docs/pull/1641 as well, in which `sw-toolbox`'s fetch handlers (inadvertantly) takes precedence over the `sw-precache`'s `fetch` handler.

The intended behavior (or at least what I think is most reasonable) is that `sw-precache`'s `fetch` handler gets first crack at requests, since if it does match a request, it can serve it immediately from the cache. This includes navigation requests when `navigateFallback` is set.

To actually accomplish that behavior I intend, I plan on moving the inlined `sw-toolbox` code to the bottom of the generated service worker JS file as part of the `sw-precache` 4.0 release. That will ensure that the `fetch` handler used by `sw-toolbox` will be skipped whenever `sw-precache`'s `fetch` handler calls `event.respondWith()`.

If you have a use case in which you need `sw-toolbox`'s handlers to take precedence, for some reason, then I'm eager to hear about it because it's something that I haven't anticipated.

**Comment by wernight** [comment]
I guess in most cases of it's part of the precache it's unlikely one would
want to override that behavior or it'd be only because it shouldn't have
been precached.

I agree that sw-precache taking precedence was my initial expectation well.

Also related, why not simply allow custom footer that can use sw-toolbox
directly? Like directly writing the last sw-toolbox in a script that
sw-precache would include. That'd be more powerful, IMO simpler

Le ven. 10 juin 2016 à 19:05, Jeffrey Posnick <notifications@github.com> a
écrit :

**Comment by jeffposnick** [comment]
#131 also moves the `importScripts()` statement to the bottom of the generated service worker file, which should accomplish what you suggest—allowing developers to pull in arbitrary custom code that executes after the `sw-precache` logic.

I'm hoping that will be the permanent arrangement and this won't require additional fiddling, but if there are folks who need custom code that executes _prior_ to the `sw-precache` handlers, which was the legacy behavior, then I'd imagine I'll split things up into separate `importScriptsEarly` and `importScriptsLate` options, or something along those lines. (But I feel like there are too many options already, and I'd like to avoid that.)

**Comment by wernight** [comment]
Agree on all your points. I'd actually deprecated the ’runtimeCaching’ option and let people directly user sw-toolbox via the ’importScript’ option. Currently some of the doc links are event broken making it really hard to grasp and actually harder to understand how and if one can actually use sw-precache with sw-toolbox.

Thanks for the replies.
