### ISSUE TITLE
Migrating from fingerprint cache

### ISSUE THREAD

**Issue by aletorrado** [GoogleChrome/sw-precache#134]
Hi, I'm considering to migrate fingerprint caching to sw-precache. Sw-precache seems a lot nicer because it's a drop-in solution, but it has an important issue for me:

The nice thing about fingerprinting is that resources are updated right away, but with sw-precache there is one page refresh when resources' old versions are served.

I don't know exactly how to deal with it. What can you suggest?

Thanks

**Comment by jeffposnick** [comment]
First off, including hash fingerprints in asset filenames and setting appropriate HTTP caching headers on your server is still a great practice. Not every browser supports service workers, and there's no reason to degrade the experience for users on unsupported browsers just to add in service worker support.

`sw-precache` plays nicely with filename fingerprints, and you can see an example of a project that uses both at https://github.com/GoogleChrome/sw-precache/tree/master/app-shell-demo. On the current `master` branch (not yet rolled out into a versioned release), there's a new [`dontCacheBustUrlsMatching`](https://github.com/GoogleChrome/sw-precache#dontcachebusturlsmatching-regex) option which will allow you to tell `sw-precache` to skip cache-busting versioned URLs, meaning that it won't have to fetch them again from the network in order to add them to the service worker cache.

But to answer your actual question—yes, needing to reload in order to pick up changes is a downside of using a cache-first strategy for your App Shell. The (significant) upside is that your App Shell is served almost instantly, directly from the cache, without having to introduce any performance variability due to uncertain network conditions.

If you really wanted to, you can add in JavaScript to automatically refresh the page whenever you [detect changes](https://github.com/GoogleChrome/sw-precache/blob/master/demo/app/js/service-worker-registration.js#L26) to the App Shell's resources. This may or may not introduce user confusion if they started interacting with the page, only to see it go away and then come right back with a slightly different look and feel.

Ultimately, though, what you're describing is working as intended, so I'm not sure there's anything actionable other than the suggestions I made.
