### ISSUE TITLE
When there's new content available

### ISSUE THREAD

**Issue by tobireif** [GoogleChrome/sw-precache#136]
From the README:

"display a toast/alert to your users when there's new content available, and give them an opportunity to reload the page to pick up that new content (which the service worker will have added to the cache, and will be available at the next page load). "

Would it alternatively be possible to let the user trigger loading of the new content without having to reload the whole page? (eg like Twitter's timeline)

**Comment by jeffposnick** [comment]
It would make sense to use a library like `sw-toolbox` instead of `sw-precache` to handle that dynamic content. `sw-precache` is intended to handle the local, static resources that make up the "shell" of your application.

You can learn more about what `sw-precache` and `sw-toolbox` does and how that relates to the App Shell + dynamic content model at

- https://www.youtube.com/watch?v=jCKZDTtUA2A
- https://developers.google.com/web/updates/2015/11/app-shell?hl=en
