### ISSUE TITLE
I can't seem to precache a 404.html page

### ISSUE THREAD

**Issue by jasan-s** [GoogleChrome/sw-precache#159]
I can precache all other files, I'm using firebase for hosting and use a 404.html page. service worker error 404 (Not Found) for the 404.html file. I know it exists and the path is correct. any suggestions?

**Comment by jeffposnick** [comment]
How is your web server configured to respond to direct GET requests for `404.html`? It sounds like it's responding with a status code of `404`, which tells `sw-precache` that the request resulted in an error, and that the response is therefore not valid.

You'd want to configure your web server so that if there's a direct GET requests for `404.html`, it should respond with the HTML contents of `404.html`, along with an HTTP status code of `200`.

Your web server can still be configured to respond to requests for invalid URLs, like GET `does_not_exist.html`, with the HTML contents of `404.html` and the HTTP status code of 404.

Your choice of web server determines what the actual configuration to get that behavior would look like, and I'm not sure that I'd be of help there.
