### ISSUE TITLE
How do i confirm that sw-toolbox urlPattern handler strategy is working as designed?

### ISSUE THREAD

**Issue by jasan-s** [GoogleChrome/sw-precache#160]
I'm using sw-toolbox with sw-precache at runtime caching option. But when i visit the url and inspect the network in devtools it shows cached from service workers not from network first (as i desire). Maybe I just don't understand how these two libs work together. My current implementation uses sw-precache to cache my entire webapp(very small webapp) and using runtime caching option i used a url pattern with handler of network first. My thought is that even-though the entire app is cached , when i go the specific url pattern the data used at the page will be fetched from network not cache. Is this incorrect?

**Comment by jeffposnick** [comment]
Requests for resources that are versioned by `sw-precache` are always going to be handled by `sw-precache`, even if there's also a `runtimeCaching` (i.e. `sw-toolbox`) route that matches the request. The `sw-precache` takes precedence.

If there's a subset of requests made to your local resources that you'd like handled via `sw-toolbox`, to make them network-first, then you can modify your [`staticFileGlobs`](https://github.com/GoogleChrome/sw-precache#staticfileglobs-arraystring) parameter so that those files are excluded from the list that `sw-precache` manages. Adding in the [`verbose: true`](https://github.com/GoogleChrome/sw-precache#verbose-boolean) parameter can help while you're trying this out, as it will give you a full list of all the files that `sw-precache` is managing.

**Comment by jeffposnick** [comment]
(I'm going to close this as hopefully that makes sense, but please re-open if further clarification is needed.)

**Comment by englishextra** [comment]
> [edited to make simple] even if there's also a runtimeCaching route that matches the request, the sw-precache takes precedence, thus network-first requests handled via sw-toolbox should be excluded from staticFileGlobs parameter

This should be stated in README.md
