### ISSUE TITLE
Using Sw-precache with firebase  (question) 

### ISSUE THREAD

**Issue by jasan-s** [GoogleChrome/sw-precache#165]
I am a bit unclear as to how to configure runtime caching option for my SPA so that I can have service worker control calls made to firebase database for data and cache the previously downloaded dynamic data beacuse on refresh the data disappers(when no network)  . Any help would be greatly appreciated. 

I don't know if its better to use something like redux-persist which saves the last state in memory so state persists through refresh. but the problem with that is if there is a change in data, how would i know?

**Comment by jeffposnick** [comment]
You can't, really, if you're using the Firebase Web Socket interface. Web Socket calls bypass the service worker completely.

If you are using the REST interface, then it's possible to have the service worker intercept those calls, but it's not necessarily going to be the best approach (and it forces you to use REST instead of the realtime API).

Instead, what I'd recommend doing is using IndexedDB to handle offline scenarios. Unfortunately, this isn't officially baked into the Firebase JavaScript SDK at the moment, so you'll have to roll your own solution.

https://www.youtube.com/watch?v=srdKq0DckXQ is @addyosmani's talk from Google I/O 2016, that goes into some detail on how he accomplished this in a sample app. You can also take a look at the open source code for the Google I/O Web App, which implements IndexedDB queueing for all read and write operations to handle offline scenarios: https://github.com/GoogleChrome/ioweb2016/blob/master/app/scripts/helper/firebase.js

**Comment by Sliqric7053** [comment]
Hi guys
Is the original issue still the case? Or has someone found a work-around? 
I am experiencing the same issue.

> 

I have the same problem as the asker of this question (https://www.stackoverflow.com/questions/50574401/service-worker-not-working-for-external-images-only ), Specifically, I’ve stored my images on Firebase Storage, the access url of which I’ve inserted as a property (i.e. logo-url) into my “members” collection (in Firestore), which I call from a service in Angular 6 and subscribe to it in one of the components. How can I get my Service Worker (ngsw) to cache these images?

**Comment by aSegatto** [comment]
same problem here, the sw is not caching the images on the storage....
