### ISSUE TITLE
Runtime caching polymer and angularJs

### ISSUE THREAD

**Issue by kapoorji** [GoogleChrome/sw-precache#175]
I am routing my application to angular and polymer, like below is the route for my angular:

```
    app.get('/tool', function (req, res) {
        res.render('tool', { layout: false, env: process.env.NODE_ENV });
    });
```

this is the runtimeCaching, i am providing
```
        runtimeCaching: [
            {
                urlPattern: /\/tool/,
                handler: 'cacheFirst'
            },
```
App url : http://localhost:23448/tool/#/
same like in case of polymer 
```
            {
                urlPattern: /\/support\/#\//,
                handler: 'cacheFirst',
                options: {
                    cache: {
                        maxEntries: 2,
                        name: 'support-cache'
                    }
                }
            }
```
App url : http://localhost:23448/support/#/

I am not sure is this the way to cache single pager application or is it an regex issue as my other routes are getting cached except SPA where url is getting appended with '#' .
Any help is appreciated. Sorry I couldn't narrow it down further.

**Comment by jeffposnick** [comment]
URL fragments (`#` and everything that follows) aren't (currently; at least until https://github.com/w3c/ServiceWorker/issues/854 is implemented widely) exposed to the service worker and changes to the URL fragment via the History API won't trigger a service worker fetch.

But anyway, it sounds like what you want is to switch to "real" URL modification instead of URL fragments in your client-side code (via [this option](http://stackoverflow.com/questions/14319967/angularjs-routing-without-the-hash) in Angular) and then using the [`navigateFallback`](https://github.com/GoogleChrome/sw-precache#navigatefallback-string) option in `sw-precache` to cause all navigation requests to go to your main App Shell URL, which in your case is `/tool`. There's an example in the [Getting Started Guide](https://github.com/GoogleChrome/sw-precache/blob/master/GettingStarted.md#fallback-url).

**Comment by kapoorji** [comment]
Thank you so much Jeff for reverting
