### ISSUE TITLE
Service Worker cache never hit.

### ISSUE THREAD

**Issue by moimael** [GoogleChrome/sw-precache#179]
Hi,

I'm trying to use sw-precache with a webpack plugin (https://www.npmjs.com/package/sw-precache-webpack-plugin). The caching part work fine, the service worker is registered and running. But no matter what I try, the browser never serve cache from the service worker.

(Also, not sure if related, but we use Server Side rendering for first page load).

Here are some screenshot : 

SW activated and running on first page load : 
![sw](https://cloud.githubusercontent.com/assets/1479859/18467114/f1d64808-799e-11e6-9813-d272c63fd83a.png)

Assets downloaded and ready to be served:

![console-sw](https://cloud.githubusercontent.com/assets/1479859/18467134/05776b1c-799f-11e6-939f-8f4498ea053c.png)
![cache](https://cloud.githubusercontent.com/assets/1479859/18467145/0d946fd4-799f-11e6-8aa7-fa6870b09593.png)

But trying to reload the page many times and SW cache is never hit : 
![network](https://cloud.githubusercontent.com/assets/1479859/18467161/1fee983a-799f-11e6-9e5a-36328ba664ed.png)

Any idea of what I might be doing wrong ?

Thanks !

**Comment by jeffposnick** [comment]
The scope of your service worker registration is `/galaxy-assets/dist/`. Based on what I can see from your Network panel screenshot, I believe that the page you're accessing is served from `/careers`. Because `/careers` isn't a subpath of `/galaxy-assets/dist/`, your visit to `/careers` won't be controlled by the service worker.

The easiest approach would be to move your `galaxy-service-worker.js` file up to the top-level of your site, and then use `navigator.serviceWorker.register('/galaxy-service-worker.js');`. A top-level service worker will have a scope of `/`, which means that all pages on your site will fall under its control.

**Comment by moimael** [comment]
It was indeed the problem, sorry for the newbie mistake, I'm very new to service workers :)
Thanks for your help ! We now achieve sub 0.5s load time with sw-precache :)

**Comment by jeffposnick** [comment]
No worries! Glad it's working.
