### ISSUE TITLE
FR: Changing the execution point of `importScripts`

### ISSUE THREAD

**Issue by choumx** [GoogleChrome/sw-precache#181]
Hey folks!

I'm working on a PWA that progressively enhances existing content pages on a site by having the service worker to return the app shell for those URLs (the app would then render the content within the shell). I'm currently also caching these pages via sw-precache.

To do this, I can introduce an additional `fetch` event listener in the service worker via `importScripts`. But this would need to preempt the existing `fetch` event listener, which currently isn't possible since `importScripts` is executed at the bottom of the generated service worker.

I can get around this by using `templateFilePath`, but it seems like a waste to dupe the original template just to reorder `importScripts`.

WDYT about adding an option to change the execution point of `importScripts` to preempt the generated event listeners? I can take a stab at this if you think it's worthwhile.

**Comment by jeffposnick** [comment]
Hello @choumx!

`sw-precache`'s `fetch` event listener will only call `FetchEvent.respondWith()` iff the request is for something that `sw-precache` "knows about". In other words, if it's a request for one of the URLs that `sw-precache` actively manages, or if it's a navigation request and [`navigateFallback`](https://github.com/GoogleChrome/sw-precache#navigatefallback-string) is set.

If there's a request that doesn't meet those criteria, then `sw-precache`'s `fetch` handler won't call `respondWith()`, and the next registered `fetch` event handler will get its chance to respond. If none of the registered `fetch` event handlers call `respondWith()`, then the request will be handled as if there were no service worker at all (going against the HTTP cache or the network).

You can see this in action in the general case in this [sample](https://googlechrome.github.io/samples/service-worker/multiple-handlers/index.html).

What that all means is that it shouldn't matter if your `fetch` handler is registered second, since it will still get a chance to respond to requests that `sw-precache` doesn't handle. If there's a request that `sw-precache` is handling and you'd prefer to handle instead, you should change the `sw-precache` configuration to, e.g., remove the resource from the [`staticFileGlobs`](https://github.com/GoogleChrome/sw-precache#staticfileglobs-arraystring) list, and then `sw-precache` will stop handling it.

Please re-open if that doesn't address your question!

**Comment by choumx** [comment]
Thanks for the response! Sorry I could've said that more clearly -- for the resource in question, I still want it to be cached by `sw-precache`. What I'd like is for the service worker to perform special logic that preempts the return of the cached content under certain conditions. I.e.
```
self.addEventListener('fetch', e => {
  // Don't return cached content for resource X under certain conditions, e.g. navigation.
  if (e.request.mode === 'navigation') {
    e.respondWith('somethingElse');
  }
});

self.addEventListener('fetch', e => {
  // sw-precache's returns cached content for resource X.
});
```
That being said, I'm not sure this would be better than using `templateFilePath` (which I'm currently doing).

**Comment by jeffposnick** [comment]
I'd recommend excluding it from from `staticFileGlobs`, and manually implementing logic (precaching, expiration, etc.) for it via a script that gets pulled in via `importScripts()`. You can use, e.g., `sw-toolbox` or vanilla Cache Storage API calls to handle that.

Having `sw-precache` include it in the list of things that it manages but allowing folks to out of the `sw-precache` `fetch` behavior is a bit of a niche case that I'm not sure that it makes sense to support officially.
