### ISSUE TITLE
sw-precache 4.2.0, build broken on bower 

### ISSUE THREAD

**Issue by chenav** [GoogleChrome/sw-precache#200]
<img width="745" alt="capture d ecran 2016-10-19 a 16 15 56" src="https://cloud.githubusercontent.com/assets/16047594/19522414/6af37f14-9617-11e6-9fa4-4f195e0ef829.png">

Impossible of running grunt script calling sw-precache. 
Fallback to 4.1.0 here seems to be working.

C.

**Comment by jeffposnick** [comment]
Hello @chenav—what version of NodeJS are you using? (Output of `node -v`.)

That code is in one of the dependencies, `pretty-bytes`, which did get its version updated in the latest `sw-precache` release. I'll take a look into how it's being used, and can roll back to a previous version of `pretty-bytes` if it comes to that.

**Comment by chenav** [comment]
Hey @jeffposnick ,

The quality server on which I test my deployment gruntfile, runs node v0.12.13.

I may have to upgrade it then.

C.

**Comment by jeffposnick** [comment]
Thanks for passing along the node version. Upgrading your server is probably a good idea, regardless, since v0.12 is currently in [maintenance mode](https://github.com/nodejs/LTS) and is scheduled to stop being supported at the end of the year.

That being said, the intention was not to force folks to update, so I'll push out something that will still maintain v0.12 compatibility via changes to how we're using `pretty-bytes`.

**Comment by jeffposnick** [comment]
(It's frustrating that Travis CI [wasn't responding yesterday](https://github.com/GoogleChrome/sw-precache/pull/199#issuecomment-254645496), because we do still test on node v0.12 there, and it would have presumably caught this. Oh well!)

**Comment by chenav** [comment]
Roger that.
The community is there to find stuff like that, rapidly :)

Anyway, thanks for your good work !

**Comment by jeffposnick** [comment]
I've pushed `4.2.1` to npm, so feel free to give it another try.

**Comment by chenav** [comment]
Works perfectly on node 0.12.13 now.

Thx.
