### ISSUE TITLE
maxEntries not working

### ISSUE THREAD

**Issue by markbrocato** [GoogleChrome/sw-precache#202]
The following creates the desired cache, but the maxEntries limit is not enforced.  The cache grows indefinitely:

```javascript
runtimeCaching: [{
	urlPattern: /\/images\/.*/,
	options: {
		cache: {
			name: "images",
			maxEntries: 5
		}
	}
}];
```

I'm using sw-precache 4.1.0.

**Comment by jeffposnick** [comment]
I think the issue is that you're not defining a `handler`. You can see an example of a valid configuration at https://github.com/GoogleChrome/sw-precache/blob/master/app-shell-demo/gulpfile.babel.js#L149

(Using `handler: 'cacheFirst'` is normally a good idea for this type of cache, if you know that the image at a given URL is unlikely to ever change.)

Apologies that this ends up being a "silent" failure. That's something we're hoping to improve in the next generation of this tooling.

**Comment by markbrocato** [comment]
Hmm... I'm pretty sure I was defining a handler and just left that out of the snippet in the report. You might want to check that it works with a handler defined. I'll have a look later as well.

**Comment by jeffposnick** [comment]
You can see it working by visiting a few items under https://ifixit-pwa.appspot.com/ and then taking a look at the `image-cache` contents in the Applications tab of Chrome's DevTools. They should max out at 50 entries:

![image](https://cloud.githubusercontent.com/assets/1749548/19605073/2cb2567e-9786-11e6-93be-fda1f6a07402.png)

That's using a config from https://github.com/GoogleChrome/sw-precache/blob/master/app-shell-demo/gulpfile.babel.js#L147

If you have a public site with a deployed service worker that's not behaving as expected, could you pass along the URL?

**Comment by markbrocato** [comment]
After some digging, I found the problem was my fault.  I overrode the networkFirst handler to add in some custom logic and wound up ignoring some of the options.  False alarm.  I'm sorry about that.
