### ISSUE TITLE
dontCacheBustUrlsMatching: /./ not working.

### ISSUE THREAD

**Issue by Hosar** [GoogleChrome/sw-precache#219]
Even when I set: `dontCacheBustUrlsMatching: /./` sw-precache still generate the precacheConfig as follow
[["css/main3cb4f06fd9e705bea97eb1bece31fd6d.css","3cb4f06fd9e705bea97eb1bece31fd6d"]].

Do I need to do something else to do not generate cache-busting parameter ?

**Comment by jeffposnick** [comment]
What you're seeing is expected. `sw-precache` still needs to know how to version the URL.

What you should not be seeing is an `_sw-prechace=<hash>` parameter appended to the end of the URL when the cache is being populated. You're telling `sw-precache` that you don't want that parameter added because you're fine if the HTTP cache is used to fulfill the precaching request.

Here's an example of what you should *not* be seeing:
<img width="386" alt="screen shot 2016-11-28 at 11 26 53 am" src="https://cloud.githubusercontent.com/assets/1749548/20676431/b9fc126e-b55d-11e6-8897-e5a3e3ee9685.png">

Instead, you should see requests with the gear icon next to them that don't end in `_sw-prechace=<hash>`.

**Comment by Hosar** [comment]
Ok got it. Thanks for clarify.
