### ISSUE TITLE
Option to force delete all old cacheName

### ISSUE THREAD

**Issue by quangrau** [GoogleChrome/sw-precache#221]
![screen shot 2016-11-28 at 4 20 45 pm](https://cloud.githubusercontent.com/assets/3326521/20662946/3772d6fe-b588-11e6-847c-cd6782268318.png)

Every time, when I pump a new version for cacheName. It doesn't delete the others cacheName. The only way I can do that is overwirte the `service-worker.tmpl` and Add function to delete all others cacheName.

```
caches.keys().then(function(keyList) {
      return Promise.all(keyList.map(function(key) {
        if (key !== cacheName) {
          console.log('[ServiceWorker] Removing old cache', key);
          return caches.delete(key);
        }
      }));
    }),
```

So, should we have an option for this? If not, when the browser will be delete these keys?

**Comment by jeffposnick** [comment]
In general, there's no need for you to manually change `cacheName` when you update your local resources. `sw-precache` automatically manages the single cache that it creates, so you don't have to worry about cleaning anything up. Since changing `cacheName` frequently isn't an anticipated use case, there are no plans to add in helpers to clean up caches that don't match the current expected name.

`cacheName` is useful when you're working on multiple service worker-enabled projects that all might be served from the same `localhost` domain:port, e.g. `http://localhost:8000`. It helps ensure that each of them have a cache with a unique name, so that you don't end up overwriting the caches whenever you switch from local project to local project.

It's safe just to leave `cacheName` empty if you're not worried about working with multiple projects locally.
