### ISSUE TITLE
Handle non-static js files

### ISSUE THREAD

**Issue by tanx** [GoogleChrome/sw-precache#23]
Thanks for the awesome lib. Very useful.

I'm having trouble adding dynamic files that are not yet available during build time. E.g. `http://localhost:8889/socket.io/socket.io.js` is a js file that gets served by the socket.io server at runtime:

    dynamicUrlToDependencies: {
        'socket.io/socket.io.js': ['socket.io/socket.io.js'],
    }

Unfortunately this throws the following error when running the grunt script:

    Warning: ENOENT, no such file or directory 'socket.io/socket.io.js' Use --force to continue.

Am I missing something or can you only add static files to the precache?

Thanks

**Comment by jeffposnick** [comment]
`sw-precache` wants a actual local file(s) listed in `dynamicUrlToDependencies` array value for a given URL key, because it needs to generate an MD5 hash to determine whether anything has changed in the file. This ensures that the library can expire out of date cache entries when it detects a change during the build process. So yes, you can only have static files as the dependencies in that array.

In your case, it looks like the underlying static file that gets served by the runtime server corresponds to `node_modules/socket.io/node_modules/socket.io-client/socket.io.js`, so that's what you should use in the array.

**Comment by tanx** [comment]
Ok. That works now thanks.

One quick general question: if I wanted to add my own service-worker logic e.g. push notifications to the generated service-worker.js file how would I go about doing that?

**Comment by jeffposnick** [comment]
You can put event listener code, etc. in a standalone JS file and use the [`importScripts`](https://github.com/GoogleChrome/sw-precache#importscripts-arraystring) option to pull it in to the service worker's context.

**Comment by tanx** [comment]
Interesting. Will the SW files be concatinated or minified in some way to reduce the networkf load?

**Comment by jeffposnick** [comment]
`sw-precache` won't process your JS file in any way. As you can see in the [source code](https://github.com/GoogleChrome/sw-precache/blob/master/service-worker.tmpl#L26), it's just making an [`importScripts()`](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts) call, passing in whatever URLs you specify.

You can minify your JS file and/or concatenate multiple JS files before calling `sw-precache`, and pass in the URL of the processed file using the `importScripts` option.

**Comment by fedex1** [comment]
@jeffposnick One question if our web application depends on jquery or some other javascript are we supposed to copy the files locally before running ./cli.js or gulp?

And if so what about the google visualization library, etc.  And what if those scripts load other resources, do we copy it all locally or is there a tool to automate this?

I see at https://github.com/jakearchibald/trained-to-thrill/blob/master/src/js/sw/index.js (relevant part shown below)

but all the examples do not seem to include third party javascript code.

(small question, Jake seems to refer to cache.addAll below but that does not seem to be in chrome canary)

```javascript
self.oninstall = function(event) {
  self.skipWaiting();

  event.waitUntil(
    caches.open(staticCacheName).then(function(cache) {
      return cache.addAll([
        './',
        'css/all.css',
        'js/page.js',
        'imgs/logo.svg',
        'imgs/icon.png'
      ]);
    })
  );
};
```

**Comment by fedex1** [comment]
Another question related to static files,  I've downloaded jquery and google visualization javascript files.

And added them to the gulpfile.js

They are in the /js/ext directory

```javascript

  staticFileGlobs: [
      rootDir + '/css/**.css',
      rootDir + '/**.html',
      rootDir + '/images/**.*',
      rootDir + '/js/**.js',
      rootDir + '/js/ext/**.js'
    ]
```

And it all works fine with the caching of the files.

But the google chart code seems to only work online (which may be expected, but it would be nice if google charts worked offline :+1:   :)

For example see: https://civic-data.github.io/sw-precache/

# With network I see:


![screen shot 2015-05-03 at 10 33 00 pm](https://cloud.githubusercontent.com/assets/167614/7448314/8ac257ee-f1e4-11e4-9e6d-14df82446fcc.png)

# *Without* network I see:
![screen shot 2015-05-03 at 10 33 25 pm](https://cloud.githubusercontent.com/assets/167614/7448313/8ac25a82-f1e4-11e4-844b-de084c0c1ac7.png)

**Comment by jeffposnick** [comment]
`sw-precache` has a very specific use case—precaching local, static(ish) files. This takes care of a lot of use cases, but won't have any runtime caching scenarios—like what you're need to ensure that a remote resource is cached, or what you'd need to provide a fallback if an API call fails because you're offline.

I'd recommend taking a look at https://github.com/googlechrome/sw-toolbox for those runtime caching scenarios. Using `sw-precache` for all your local, static content and then supplementing it with `sw-toolbox` is definitely legitimate. You can pull in the `sw-toolbox` code via that same `importScripts` options I was talking about upthread.

**Comment by fedex1** [comment]
thank you very much
