### ISSUE TITLE
Move PrecacheConfig to external file

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChrome/sw-precache#236]
Generated `service-worker.js` files are identical except `PrecacheConfig` variable. What about move `PrecacheConfig` to external file?

**Comment by jeffposnick** [comment]
That's intentional. Changing the generated `service-worker.js` file itself is necessary in order to [trigger the service worker update flow](https://developers.google.com/web/fundamentals/instant-and-offline/service-worker/lifecycle#updates), which is what is responsible for caching the updated resources.

As of right now, updates to external files that get pulled in to the main service worker via `importScripts()` won't trigger the service worker update flow, so it's possible to move the file hashes to an external file. This will change in the future, as the service worker specification [has been modified](https://github.com/w3c/ServiceWorker/pull/1023) to allow changes to files pulled in via `importScripts()` to trigger the update flow. However, until all browsers with service worker support are updated to this new behavior, we can't change the current approach.

**Comment by FluorescentHallucinogen** [comment]
What about leave this issue open until all browsers with service worker support are updated to this new behavior?
