### ISSUE TITLE
Exception not caught by promise

### ISSUE THREAD

**Issue by felixhammerl** [GoogleChrome/sw-precache#24]
hi guys, 

thanks for this cookbook! quick question about your demo code:

https://github.com/GoogleChrome/sw-precache/blob/b24c548995606a7c1b2cef670b97fd120d66ba09/demo/app/js/service-worker-registration.js#L63

`onstatechange` is an asynchronous api, hence this exception would not be caught by the promise, right? should this not be wrapped in a new promise with a `reject()` here?

cheers
felix

**Comment by jeffposnick** [comment]
@felixhammerl—That's a good point. The exception won't be handled by the outer `catch()` since it's thrown during the event handler, outside the Promise.

I don't know that there's really a best practice around how you report the `redundant` state (it depends on the structure of the larger web app), but I can switch it to be a `console.error()` call instead of an exception instead.
