### ISSUE TITLE
Sample webpack.js examples

### ISSUE THREAD

**Issue by TheoMer** [GoogleChrome/sw-precache#250]
Are there any sample webpack.js examples available for sw-precache?

**Comment by jeffposnick** [comment]
Integration via https://www.npmjs.com/package/sw-precache-webpack-plugin is the current recommendation.

There are examples in the docs for that module.

**Comment by natecox** [comment]
I think there's a wider question here of, "Does sw-precache want to provide implementation examples for common setups?" E.g., I recently had to set sw-precache up with Phoenix/Brunch, and the result is going to become at least partially boilerplate code for me in future projects. It would have been handy to have the boilerplate part provided for me.

**Comment by jeffposnick** [comment]
We've traditionally limited ourselves to linking out to specific projects in the "[Wrappers and Starter Kits](https://github.com/GoogleChrome/sw-precache#wrappers-and-starter-kits)" section of the README.

Given the wide range of possible build setups and the limited experience that I have with some of them, that seems to be the most scalable approach, rather than try to capture canonical examples in this repo.

If there are other helpful recipes or boilerplate that you'd like linked to, I'm happy to accept PRs modifying that section of the README.

**Comment by natecox** [comment]
@jeffposnick I'm willing to issue a pull request to add a Gist if you think that would be appropriate to add to the section: https://gist.github.com/natecox/b19c4e08408a5bf0d4cf4d74f1902260

Right now it seems what's there is a bit more robust than a bit of sample code, so I'm not sure if that really fits.

**Comment by jeffposnick** [comment]
I think it could still be useful to include that, perhaps in the "[Recipes for writing a custom wrapper](https://github.com/GoogleChrome/sw-precache#recipes-for-writing-a-custom-wrapper)" section.

PRs welcome.

**Comment by natecox** [comment]
Can do: https://github.com/GoogleChrome/sw-precache/pull/251#issuecomment-281447087
