### ISSUE TITLE
caching remote resources

### ISSUE THREAD

**Issue by atsepkov** [GoogleChrome/sw-precache#268]
How do I cache files located on another server? For example, if I use cloudflare version of angular library or bootstrap and want both of them to be available in offline mode, yet they won't be picked up by the `sw-precache` profiler. Even if I explicitly mention them in the config file, they still will get excluded because the name glob pattern won't match against anything local. Is there a way to handle such use case with this library?

This doesn't seem to be a service-worker limitation, since I'm finding examples online doing this with vanilla service-worker: https://googlechrome.github.io/samples/service-worker/prefetch-video/

**Comment by jeffposnick** [comment]
`sw-precache` will only cache and update local files. It needs to generate a hash for each resource during the build process, which implies that the files are present locally.

If you have resources on a CDN that you'd like cached, you can employ a [`runtimeCaching` strategy](https://github.com/GoogleChrome/sw-precache#runtimecaching-arrayobject) to add those. If the URL contains a versioning string, e.g. `v1.0.0`, like most CDN URLs include, you can safely use a `cacheFirst` handler, since you know that the resource at that URL will never change:

```js
runtimeCaching: [{
  urlPattern: new RegExp('^https://cdn\.example\.com/'),
  handler: 'cacheFirst'
}]
```

If there is no versioning information in the URL, then you'd probably want to use the `fastest` (stale-while-revalidate) or `networkFirst` handler, to ensure that the cached response gets updated eventually.
