### ISSUE TITLE
How to define in sw-precache-config.js a generic placeholder image fallback on runtimeCaching request

### ISSUE THREAD

**Issue by aguerot** [GoogleChrome/sw-precache#274]
Hi,

I am seting a PWA using sw-precache-config.js and I would like to define a rule whereas profile image must first be downloaded from the network, if not available from cache and finally if cache is empty, use a generic static cached placeholder image.

Such as scenario is detailed [here](https://developers.google.com/web/showcase/2015/service-workers-iowa) under Speaker Profile Image section from a code point of view. I am trying to do the same with a config.

Here is an extract of my config
`
staticFileGlobs: [
    ...
    'dist/assets/images/placeholders/*.{png,jpg}', // this is the generic placeholder image
    ...
  ],

  runtimeCaching: [
    {
       urlPattern: /\/\/lorempixel.com\/*/,
      handler: 'networkFirst',
      // HERE how can I express the fact that if network and cache fail I want to return default profile
      // dist/assets/images/placeholders/profile.png
    }
  ]
`

Any help in defining such a rule in config would be greatly appreciated.

**Comment by jeffposnick** [comment]
That's the sort of thing that's difficult to express in a configuration file. What I'd recommend instead of using `runtimeCaching` is to put the logic into a standalone `fallback-image.js` file, and then use `importScripts: ['fallback-image.js']` to pull in your custom code.

`fallback-image.js` could look something like:

```js
// Assume that the image at this URL is already cached via sw-precache.
const fallbackImage = 'path/to/fallback.png';

toolbox.router.get(
  new RegExp('lorempixel\.com'),
  request => toolbox.cacheFirst(request).catch(() => caches.match(fallbackImage))
);
```

That assumes that `toolbox` is already defined, which will happen automatically if you're using `runtimeCaching` for other purposes (it causes `sw-toolbox.js` to get inlined into the generated service worker file). If you're not using `runtimeCaching` for anything else, then you'll want to pull in `sw-toolbox.js` alongside your `fallback-image.js`, via `importScripts: ['path/to/sw-toolbox.js', 'fallback-image.js']`.

**Comment by aguerot** [comment]
Thanks for your feedback.
