### ISSUE TITLE
Clear storage for navigateFallback

### ISSUE THREAD

**Issue by seejamescode** [GoogleChrome/sw-precache#278]
Thanks for this tool! I use the Create-React-PWA implementation and this is really helpful. I recently added React Router v3 to a project and followed the `navigateFallback: 'index.html'` instructions here: https://github.com/jeffposnick/create-react-pwa#ive-added-in-react-router-and-now-my-urls-dont-work-offline

However, now I have to `Clear Site Data` in the Chrome DevTools to see the update to my app. Do you know what may be wrong with my implementation?

Is there more information I could provide you for help?

**Comment by jeffposnick** [comment]
Hello @seejamescode—Since `sw-precache` employs a cache-first strategy for all the resources it manages, it's expected that you won't see updates to those resources until the "N+1" visit to a page.

Another wrinkle is that the updates get triggered whenever the `service-worker.js` file actually changes, and HTTP caching headers can affect when those changes are detected. There's more information at http://stackoverflow.com/a/38854905/385997, but the tl;dr is to make sure that you disable HTTP caching for your `service-worker.js`.

**Comment by seejamescode** [comment]
Thanks @jeffposnick!
