### ISSUE TITLE
Couldn't serve response for "%s" from cache: %O

### ISSUE THREAD

**Issue by Akta3d** [GoogleChrome/sw-precache#289]
Sometime response is not in the cache and we have this log : 
Couldn't serve response for "%s" from cache: %O

Is it a good idea to request the resource from server and put it in the cache by modifying the code as follow : 

```
.catch(function(e) {
          console.warn('Couldn\'t serve response for "%s" from cache: %O', event.request.url, e);
          return fetch(event.request);
        })
```
to
```
.catch(function(e) {
          console.warn('Couldn\'t serve response for "%s" from cache: %O', event.request.url, e);
          //return fetch(event.request);
           return fetch(event.request).then(function(response) {
              if (response.ok) {
                caches.open(cacheName).then(function(cache)
                {
               cache.put(CurrentCacheNamesToAbsoluteUrl[cacheName], response);   
                });
               
              }});
        })
```

**Comment by jeffposnick** [comment]
While that's theoretically possible, I've deliberately avoided doing that because `sw-precache` assumes that there's a match between the hash it maintains for a given URL and what's actually stored in the cache, and that those caches are only managed as part of the `install` and `activate` events.

By populating `sw-precache`'s cache with a copy of a response at runtime, that guarantee can no longer be maintained.

The only reason why a user *should* end up in the state where `sw-precache` can't find a match is if they explicitly go out of their way to delete those cached entries, and in that scenario, my preference is to continue logging the error and falling back to the network.
