### ISSUE TITLE
Duplicate asset downloads?

### ISSUE THREAD

**Issue by noise-machines** [GoogleChrome/sw-precache#304]
Hi folks,

Thanks for the excellent work on this library. Very much appreciate what you've done, and the dedication you're supporting it with.

I've got a quick question that perhaps someone can help out with. On my site, I'm seeing duplicate asset downloads. You can see what I'm talking about in this screenshot:

<img width="1440" alt="sw-precache duplicate asset downloads" src="https://cloud.githubusercontent.com/assets/5033974/26750305/f42cf6ca-47ec-11e7-934a-f79fd7bc219d.png">

Seems like the bundle is getting downloaded as part of the main page, then downloaded again to be cached by the service worker. I've done some thinking and haven't been able to devise a way around this, but I thought you might have some ideas. 

The site is live at https://v2.partials.co, and you're welcome to poke around. Source code is [in this repo](https://github.com/noise-machines/partials-co/tree/v2). In particular, my service worker registration code is [here](https://github.com/noise-machines/partials-co/blob/v2/src/awaitServiceWorkerRegistration.js).

Thanks again for your hard work.

**Comment by jeffposnick** [comment]
The additional requests coming from the SW, representing the precached assets, are expected. What you can do, though, is tell `sw-precache` not to cache-bust (via that `?_sw-precache=` parameter) a subset of your assets.

You do that via the [`dontCacheBustUrlsMatching`](https://github.com/GoogleChrome/sw-precache#dontcachebusturlsmatching-regex) parameter. In general, it should be safe to skip cache-busting for assets that already include hashes in their filenames, like the asset you highlighted in your screenshot.

Assuming you're always going to use an 8 character hash separated by `.` characters, a safe configuration option would be:

```js
{
  // Other sw-precache configuration options...
  dontCacheBustUrlsMatching: /\.\w{8}\./,
}
```

You'll still see a request made for those assets, but assuming they have the proper HTTP cache headers set and they're previously been requested by your page, they'll be fulfilled from the HTTP disk cache rather than require transferring data over the network.
