### ISSUE TITLE
dynamicUrlToDependencies Tightly coupled

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-precache#57]
I've just faced a non-obvious issue with build process for app-shell.

I was hitting an issue where my CSS wasn't getting updated in the app shell. What I realised is that the endpoint '/app-shell' inlines a CSS file, which means that as far as  sw-precache is concerned the css file is a template - this results in a oddly tight coupling of what my server is doing and what sw-precache is doing.

I'm not sure of a nice way of getting around this. In an ideal world sw-precache would just look at the endpoint and do a diff based on latest content - but this ends up requiring a server running to work.

**Comment by jeffposnick** [comment]
Yeah, it's unfortunate that you need to reflect that dependency on your CSS file in the `dynamicUrlToDependencies` config, while that dependency is also implicitly defined via whatever your server rendering process is doing.

I don't know of a generic solution to this problem. I could hypothetically imagine hacking together some way of running a local server as part of the `sw-precache` generation process, and then instead of using a composite hash-of-hashes to version dynamic URLs, using a hash of the full output HTML. But... I don't know how doable that is. If we were going to take that approach, it should probably be encapsulated in a new option, instead of modifying `dynamicUrlToDependencies` behavior.

FWIW, this is the setup I'm using for the demo that ships with `sw-precache`: https://github.com/GoogleChrome/sw-precache/blob/master/app-shell-demo/gulpfile.babel.js#L127

**Comment by jeffposnick** [comment]
I don't have any better ideas now than I did back when this issue was opened, so I'm going to close it as not feasible. 😦
