### ISSUE TITLE
"Couldn't serve response for..." and "net::ERR_FILE_EXISTS" errors encountered when reloading the page after clicking "Clear Cache"

### ISSUE THREAD

**Issue by jjinux** [GoogleChrome/sw-precache#70]
Start the demo app using "gulp serve-dist".
Load the URL (http://localhost:3000/).
Use "chrome://serviceworker-internals/" to unregister the ServiceWorker.
Reload the page.
Click "Clear Cache".
Reload the page.
You'll get a bunch of errors:

Couldn't serve response for "http://localhost:3000/" from cache: Error: The cache sw-precache-v1-sw-precache-http://localhost:3000/-http://localhost:3000/index.html-d378b5b669cd3e69fcf8397eba85b67d is empty

GET http://localhost:3000/service-worker.js net::ERR_FILE_EXISTS

See the attached screen shot.

**Comment by jjinux** [comment]
![screen shot 2015-12-17 at 3 44 19 pm](https://cloud.githubusercontent.com/assets/74551/11885557/6eae5108-a4d5-11e5-8029-cb7357447759.png)

**Comment by jjinux** [comment]
Hmm, if I play with it enough, I can get this to happen even if I don't click "Clear Cache". For instance, if I restart the server, click on the location bar in Chrome, and hit enter, I'll see this error.

**Comment by jeffposnick** [comment]
The `net::ERR_FILE_EXISTS` is some really unfortunate noise that was adding to the Chrome DevTools and is confusing lots of folks. See http://stackoverflow.com/questions/33328579 and https://code.google.com/p/chromium/issues/detail?id=541797. It should be a harmless error though.

Unfortunately, there's nothing that could be done in `sw-precache`, as it applies to all service workers.

The error about not being able to serve the response from the cache is... because you explicitly cleared the cache :smile: Maybe I should remove that "Clear Cache" button if you found it confusing—it was there to illustrate a "emergency bail out" technique that I doubt many people will end up needing.

In general, I'd recommend playing around with service workers in an Incognito window, since it makes it easier to start fresh and then experiment, and then start fresh again after you reopen the Incognito window.
