### ISSUE TITLE
When is app shell updated?

### ISSUE THREAD

**Issue by owencm** [GoogleChrome/sw-precache#76]
This is probably a silly question, but I've used sw-precache for my site which worked great initially, but the only way I'm seeing the cached files updating is if I unregister the service worker.

When using this in production, when are the cached files supposed to update themselves? Am I doing something wrong perhaps?

**Comment by jeffposnick** [comment]
The cache should be refreshed whenever you regenerate your SW file and there were underlying changes to the files it tracks. That will cause the SW file to include new hashes in the output, which will in turn trigger the SW update flow. As part of the `install` handler, the updated file(s) are fetched and cached, and any older versions of the same file are purged. Once the SW update flow completes, you'll need to reload the current page, and you should see the new resources.

If you're not seeing this behavior, could you point me to your deployed site so that I can investigate further?

**Comment by owencm** [comment]
Ahh I see. I generated the SW once with the command line and used that, assuming it would act somewhat like stale-while-revalidate and be fetching my resources in the background to check if they're new.

Perhaps it's worth clarifying in the readme somewhere.

I'll go ahead and add this to my build process instead which I imagine will solve the issue. 

Thanks!

**Comment by jeffposnick** [comment]
#78 contains an update to the language in the README. Let me know what you think.

**Comment by jasan-s** [comment]
@jeffposnick , I have added sw-precache to my build process and do see the hashs changing for the chnaged file on the generated sw file. But after my build I update my hosted static files for my webapp
. Yet, i dont see any changes on page reload, I have to check update on reload or unregister and register the SW to see the changes.

**Comment by jasan-s** [comment]
I dont know if this is the cause but the get request for my service-worker.js from my hosted app(firebase hosting)has a header of cache-control = 3600. If this is can you suggest a solution

**Comment by jasan-s** [comment]
@jeffposnick  I changed firebase config so my sw-registration.js and my-project-sw.js both have cache control max-age =0. Now the update registers on reload in the Service worker, But I am curious as to if this will have any negative effects that i'm not seeing.

**Comment by jeffposnick** [comment]
Using a short or zero `max-age` for your service worker JavaScript file is normally a good idea. See http://stackoverflow.com/questions/38843970/service-worker-javascript-update-frequency-every-24-hours/38854905#38854905 for more context about that.
